version: 2
updates:
  - package-ecosystem: pip
    directories:
    - /.github
    - /src
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly